iOS: Correct Info.plist CFBundleVersion version string
This is analogous to the macOS Info.plist fix 5c2f06bfc4 / #146030,
copied commit message:

This commit changes the Blender iOS app bundle Info.plist
`CFBundleVersion` key to use the "short" version string (X.X.X) instead
of the "long" version string (X.X.X + date), following the specs.[^1]

This fixes an issue with Xcode bundle archiving where the previous long
version would cause an error to be thrown during archive validation:

```
ERROR: [ContentDelivery.Uploader.6000007BD0C0] CFBundleVersion, “5.0.0 2025-09-09”,
must be composed of one to three period-separated integers. (-19239)
```

The previous "long" version string is still used by the `CFBundleGetInfoString`
key and thus still shows up in the application informations

[^1]: https://developer.apple.com/documentation/bundleresources/information-property-list/cfbundleversion?language=objc